### ISSUE TITLE
Encode ISO8859_15 doesn't work

### ISSUE THREAD

**Issue by rado31** [fabienbellanger/escpos-rs#30]
- # Problem
## Letters like: äöüýşňž, ÄÖÜÝŞŇŽ - aren't printed properly. Chinese letters are printed instead of them

- # Thermal printer model
## **Xprinter XP-T80A**

- # Environment

1. OS Window 10
2. rustup 1.27.1 (54dd3d00f 2024-04-24)
3. rustc 1.80.1 (3f5fd8dd4 2024-08-06)
4. cargo 1.80.1 (376290515 2024-07-16)
5. Cargo.toml

```toml
[package]
name = "printer"
version = "0.1.0"
edition = "2021"

[dependencies]
escpos = { version = "0.13.0", features = ["full"] }
rusb = "0.9.4"
```

6. Code
```rust
use escpos::{
    driver::UsbDriver,
    errors::Result,
    printer::Printer,
    printer_options::PrinterOptions,
    utils::{DebugMode, PageCode, Protocol},
};

fn main() -> Result<()> {
    let driver = UsbDriver::open(8137, 8214, None)?;

    let options = PrinterOptions::new(Some(PageCode::ISO8859_2), None, 42);

    let mut printer = Printer::new(driver, Protocol::default(), Some(options));

    printer.debug_mode(Some(DebugMode::Dec)).init()?;

    printer.writeln("äöüýşňž")?.feeds(3)?.print_cut()?;

    Ok(())
}
```
